### ISSUE TITLE
Invoking some callback function twice leads to Segmentation fault: Nan

### ISSUE THREAD

**Issue by JasurN** [nodejs/nan#684] opened 2017-08-09 13:47 UTC
Hello! There is some problem. When I implement like this [stackoverflow link](https://stackoverflow.com/questions/45589254/invoking-some-callback-function-twice-leads-to-segmentation-fault-nan) . Please, see it. I will be appreciated for your help!

**Comment by kkoopa** [comment] 2017-08-09 14:03
You are doing multithreading wrong. V8 is not thread-safe, so it crashes when the other thread does anything related to V8. The Execute method of the AsyncWorker already runs in its own thread. Put your demanding computation there and remove everything related to thread management.

**Comment by JasurN** [comment] 2017-08-09 14:40
@kkoopa Yes, thank your answer! If it is possible, can please you help me to fix this issue? Because, program sometime generates such callbacks using its own thread.

**Comment by JasurN** [comment] 2017-08-10 07:27
//c++ code
class CallbackRunner : public Nan::AsyncWorker {
public:
    CallbackRunner(Nan::Callback *callback)
            : AsyncWorker(callback) {}
    void Execute() {

    }
    void HandleOKCallback() {
        std::cout << "running HandleOKCallback in thread " << std::this_thread::get_id() << std::endl;
        Nan::HandleScope scope;
        v8::Local<v8::Value> argv[] = {
                Nan::New<v8::Number>(10)
        };
        callback->Call(1, argv);
    }
};

struct HeaderExample {
    void callJS(nbind::cbFunction &callback) {
        std::cout << "running callJS in thread " << std::this_thread::get_id() << std::endl;
        m_onInitialisationStarted = new nbind::cbFunction(callback);
        Nan::Callback *callbackNan = new Nan::Callback(m_onInitialisationStarted->getJsFunction());
        runner = new CallbackRunner(callbackNan);
    }

    void some() {
        std::cout << "some"<< std::endl;
        std::cout << "running some in thread: " << std::this_thread::get_id() << std::endl;
        if (runner) {
            AsyncQueueWorker(runner);
        }
    }

    nbind::cbFunction *m_onInitialisationStarted = 0;
    CallbackRunner *runner;
};

**Comment by bnoordhuis** [comment] 2017-08-10 07:53
I'll close this out.  You know what the cause is now and this tracker is not a place to get the bugs in your code fixed free of charge.

**Closed by bnoordhuis** 2017-08-10 07:53 UTC
