### ISSUE TITLE
help, I can get my module compiled

### ISSUE THREAD

**Issue by x13machine** [nodejs/nan#378] opened 2015-07-16 21:58 UTC
https://gist.github.com/x13machine/91fb2152d0600ef8a6
When I do npm install get error: ‘New’ was not declared in this scope
  Local<FunctionTemplate> tpl = NanNew<FunctionTemplate>(New); I don't know what to do about it

I'm trying to get this code compiled for my game. I haven't any progress on the game for a month. I need this code in c++ because the javascript version is to slow. I don't know where else to ask.

I accidentally press, submit too soon. title doesn't make any sense

**Comment by bnoordhuis** [comment] 2015-07-17 08:53
The link 404s.  The error message suggests the issue is with your code, not nan, and this isn't a general purpose help forum.  I'm closing the issue, unless you can demonstrate it's a problem with nan.

**Closed by bnoordhuis** 2015-07-17 08:53 UTC
