### ISSUE TITLE
Is there an doc for supported node version ?

### ISSUE THREAD

**Issue by Pana** [nodejs/nan#449] opened 2015-09-11 10:46 UTC
We only know Version 2.0.9: current Node 4.0.0, Node 12: 0.12.7, Node 10: 0.10.40, iojs: 3.2.0 from the changelog, is there an doc for specific nan version support what node version ?

I think this will be useful

**Comment by mazhlekov** [comment] 2015-09-11 10:58
+1 I am trying to understand the examples and new features. It will be helpful to have updated docs.

**Comment by fivdi** [comment] 2015-09-11 11:10
Is this issue a duplicate of https://github.com/nodejs/nan/issues/368?

**Comment by kkoopa** [comment] 2015-09-11 11:27
It is a duplicate, yes. Essentially, every stable version between 0.8 and the latest available at the time of a release work.

**Closed by kkoopa** 2015-09-11 11:27 UTC

**Comment by kkoopa** [comment] 2015-09-11 11:31
Oh, and that line only lists what the latest release of each platform is at the time of a NAN release, it's not directly related to compatibility, although it in practice means that every Node release older than that should work.
