### ISSUE TITLE
does not work on Windows 10

### ISSUE THREAD

**Issue by DanielRuf** [nodejs/nan#790] opened 2018-06-17 20:27 UTC
```
    fs.createReadStream(file)
      .pipe(new lame.Decoder())
      .on('format', function (format) {
        this.pipe(new Speaker(format));
      });
```

```
PID 14740 received SIGSEGV for address: 0x51d94d1b
SymInit: Symbol-SearchPath: '.;C:\Users\Daniel\GITHUB\test;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Daniel'
OS-Version: 10.0.17134 () 0x300-0x1
c:\users\daniel\github\test\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\users\daniel\github\test\node_modules\segfault-handler\src\segfault-handler.cpp (235): segfault_handler
00007FF951D05678 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FF951CA692A (ntdll): (filename not available): RtlWalkFrameChain
00007FF951CA52CA (ntdll): (filename not available): RtlRaiseException
00007FF951D94D1B (ntdll): (filename not available): RtlIsNonEmptyDirectoryReparsePointAllowed
00007FF951D9C7E6 (ntdll): (filename not available): RtlpNtSetValueKey
00007FF951D9CAB1 (ntdll): (filename not available): RtlpNtSetValueKey
00007FF951D39A15 (ntdll): (filename not available): RtlRaiseStatus
00007FF951D4732B (ntdll): (filename not available): memset
d:\th\minkernel\crts\ucrt\src\appcrt\heap\free_base.cpp (107): _free_base
c:\users\daniel\github\test\node_modules\speaker\src\binding.cc (108): `anonymous namespace'::Close
c:\users\daniel\github\test\node_modules\nan\nan_callbacks_12_inl.h (175): Nan::imp::FunctionCallbackWrapper
00007FF749A2C7E0 (node): (filename not available): v8::internal::interpreter::Interpreter::GetDispatchCountersObject
00007FF74956BAC8 (node): (filename not available): std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::zone_allocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
00007FF74956A983 (node): (filename not available): std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::zone_allocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
00007FF74956A86B (node): (filename not available): std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::zone_allocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
000001D32E6843A1 ((module-name not available)): (filename not available): (function-name not available)
00007FF7498839FF (node): (filename not available): v8::internal::MemoryReducer::TearDown
0000000000000017 ((module-name not available)): (filename not available): (function-name not available)
000001C09EA5E3D8 ((module-name not available)): (filename not available): (function-name not available)
000001C09EACB718 ((module-name not available)): (filename not available): (function-name not available)
000001C09EA5E3D8 ((module-name not available)): (filename not available): (function-name not available)
000001C09EACB718 ((module-name not available)): (filename not available): (function-name not available)
0000034B2A2D9921 ((module-name not available)): (filename not available): (function-name not available)
000001D32E6842E1 ((module-name not available)): (filename not available): (function-name not available)
00000001000FE420 ((module-name not available)): (filename not available): (function-name not available)
0000000000000006 ((module-name not available)): (filename not available): (function-name not available)
00000001000FE4C0 ((module-name not available)): (filename not available): (function-name not available)
000001D32E8AB9C0 ((module-name not available)): (filename not available): (function-name not available)
```

**Comment by bnoordhuis** [comment] 2018-06-18 17:13
What makes you believe it's a bug in nan and not in the code that uses nan?

**Comment by DanielRuf** [comment] 2018-06-18 18:34
Because of the stacktrace, see `Nan::imp::FunctionCallbackWrapper` and it seems to be a Node.js issue.

**Comment by bnoordhuis** [comment] 2018-06-18 20:06
Just as likely it's that speaker module you have installed and uses nan; or maybe the stack trace is a complete red herring and the crash is caused by memory corruption elsewhere in your program.

There is nothing to go on here so I'm closing this pending proof that it's really a nan bug.

**Closed by bnoordhuis** 2018-06-18 20:06 UTC

**Comment by agnat** [comment] 2018-06-18 20:16
> Because of the stacktrace, see Nan::imp::FunctionCallbackWrapper and it seems to be a Node.js issue.

Hm, I don't think so. It is crashing [here](https://github.com/TooTallNate/node-speaker/blob/20627e12f2628da8313544f5a92813f78cb3e68e/src/binding.cc#L107) it would seem. To me it feels like a (subtle) stream object lifecycle bug. Looking at the code calling `speaker::Close()` twice will probably crash it...

On a side note, please take a little more time with your bug reports. Provide more context. At least state what you have tried so far and why you think it is nan's fault. If you have to fix your initial report (and mistakes happen) please state so in a separate comment. Just "Kaputt" does not cut it. Thanks.

**Comment by DanielRuf** [comment] 2018-06-18 20:20
> Hm, I don't think so. It is crashing here it would seem

Well, doesn't this call/use the nan methods?
I do not know enough C++ to pinpoint the cause but what I know so far is that the stacktrace includes `nan`.

It seems others do not have this issue which may mean that it was introduced in Node.js core or nan (I guess so).

Can you show me the right tools to easily find the culprit on Windows 10?

**Comment by DanielRuf** [comment] 2018-06-18 20:21
Also this is the whole code, nothing more.No explicit calls of `close`.

**Comment by bnoordhuis** [comment] 2018-06-18 20:27
> Sorry but I find it a bit confusing that pending bugs are directly closed like this.

I closed it because it's an insufficient bug report and most likely invalid.  Fire up VS's debugger and see what you can find.

**Comment by DanielRuf** [comment] 2018-06-18 20:30
> Fire up VS's debugger and see what you can find.

Sorry but that is new for me. I am a frontend developer and never worked with this.
I do not know how and where to start.

I tested with Node 8.0.0 and latest 10 release and got the error on both.

**Comment by bnoordhuis** [comment] 2018-06-18 20:54
I hope this doesn't come across as harsh but we're not here to help you debug your code (speaking for myself at least - but we're all busy people.)

If you can trim down your test case to something that involves _only_ nan and no other npm modules, we can take another look.

If that's not an option, file an issue with speaker.  Maybe they can help and if it does turn out to be a nan bug, they'll forward it to us.

**Comment by DanielRuf** [comment] 2018-06-18 21:09
I totally understand it. Sorry that I can not be more helpful here as I lack any real C++ experience so I guess I have to look for another solution then.
