### ISSUE TITLE
v8 5.1.281.47 issue with Nan::Null()

### ISSUE THREAD

**Issue by juliangruber** [nodejs/nan#578] opened 2016-05-31 12:22 UTC
Running electron 1.2.0, which bundles v8 `5.1.281.47` (node 6.2.0 bundles v8 `5.0.71.47`), i hit an issue where this code from leveldown (https://github.com/Level/leveldown/blob/master/src/database_async.cc#L141):

```cpp
  v8::Local<v8::Value> argv[] = {
      Nan::Null()
    , returnValue
  };
  callback->Call(2, argv);
```

calls the js callback with a boolean `true` as the first parameter.

Steps to reproduce:

create `app.js` with:

```js
var db = require('level')('/tmp/db');
db.db.put('foo', 'bar', console.log.bind(console));
db.db.get('foo', err => console.log('err', err));
```

then

```bash
$ nvm use 6
$ npm install electron-prebuilt@1.2.0 level
$ node_modules/.bin/electron app.js
```

It logs `err true`, although that argument should be `null`.

This error does _not_ happen with electron 1.1.3, which is bundling v8 `5.0.71.48`.

**Comment by mathiask88** [comment] 2016-05-31 12:42
Can't reproduce on windows. Did you run `electron-rebuild`?

**Comment by juliangruber** [comment] 2016-05-31 12:49
@mathiask88 sorry, my reproduction steps were missing a few details. can you try again?

**Comment by mathiask88** [comment] 2016-05-31 12:53
@juliangruber I meant that I could reproduce your code but not the error :) I ran the electron-starter repository with electron-prebuild 1.2.0 and level 1.4.0 and I get `null. bar`

**Comment by juliangruber** [comment] 2016-05-31 13:01
@mathiask88 hm, then it looks like this issue doesn't on windows I'd say

**Comment by mathiask88** [comment] 2016-05-31 13:30
@juliangruber Started my Ubuntu VM and it seems that `electron-rebuild` does not rebuild `leveldown` even if I use the `--force` argument. `electron-rebuild` does not have a verbose option. No NAN issue in my opinion. Maybe an error with `prebuild`? Because for windows there are no prebuilds available and it is necessary to compile.

**Comment by juliangruber** [comment] 2016-05-31 13:34
@mathiask88 the problem persists when i manually rebuild leveldown. you shouldn't need to rebuild leveldown though if you use node 6 when installing, as both node 6 and electron 1.1.3/1.2.0 have abi 48.

my problem literally disappears by issuing `npm install electron-prebuilt@1.1.3` and rerunning `app.js`.

**Comment by ofrobots** [comment] 2016-05-31 13:44
V8 5.1 is not ABI compatible with V8 5.0. Electron should not be shipping
this with ABI 48.

**Comment by ofrobots** [comment] 2016-05-31 13:53
@juliangruber Can you try this patch on top of the version of V8 5.1 included by electron: https://github.com/ofrobots/node/pull/23 and see if that solves the problem?

**Comment by 0x00A** [comment] 2016-06-02 21:25
Seems like this issue breaks most of the [`level`](https://github.com/level) projects. /cc @rvagg

**Comment by rvagg** [comment] 2016-06-03 06:23
> as both node 6 and electron 1.1.3/1.2.0 have abi 48

Wait, what?? they are shipping 5.1 and haven't changed ABI, I thought they went with a >100 number cause they were doing things differently.

**Comment by rvagg** [comment] 2016-06-03 06:27
> as both node 6 and electron 1.1.3/1.2.0 have abi 48

This is the V8 that's linked to the 1.2.0 Electron tag (via node) https://github.com/electron/node/blob/d4528c219df8f442d769bae054883e1af79f105e/deps/v8/include/v8-version.h and it says 5.0. How are you determining that you have 5.1 @juliangruber?

**Comment by kkoopa** [comment] 2016-06-03 14:03
Because it does not build Node against the bundled V8, but downloads whatever Chromium was built with and links against that. All of this is rather messed up, to say the least, but none of it pertains to NAN, so I am closing this as invalid.

**Closed by kkoopa** 2016-06-03 14:03 UTC

**Comment by juliangruber** [comment] 2016-06-03 14:24
thanks @kkoopa, that def. makes sense. I opened an issue on electron here: https://github.com/electron/electron/issues/5851
