### ISSUE TITLE
Memory leak with NAN2

### ISSUE THREAD

**Issue by krismohan** [nodejs/nan#511] opened 2015-11-06 02:04 UTC
Hi, please refer to the pull request https://github.com/oracle/node-oracledb/pull/227 for the node-oracledb driver. This updates the NAN dependency from 1.9 to 2.1 to make it work with Node 4 and higher. And we see a rapid increase in memory as the app requests are processed, which never gets released. This is observed with Node 0.10 and Node 0.12 too.

Here is some sample driver code (with no Oracle calls) that reproduces the issue. Can you please suggest a solution or fix to this? Or does it have incorrect usage of NAN? Thanks

---------------------------------------------
nanSample.h
------------------------------------------  
```c++
#include <v8.h>
#include <node.h>
#include <nan.h>

#include <string.h>
#include <stdlib.h>

using namespace node;
using namespace v8;
using namespace std;

typedef struct sampleBaton
{
uv_work_t req;
Nan::Persistent<Function> cb;
} sampleBaton;

class nanSample : public Nan::ObjectWrap
{
public:
static void Init ( Handle<Object> target );

private:
static Nan::Persistent<FunctionTemplate> sampleTemplate_s;
static NAN_METHOD(New);
static NAN_METHOD(PrintHello);
static void Async_PrintHello (uv_work_t *req );
static void Async_AfterPrintHello ( uv_work_t *req ) ;
nanSample ();
~nanSample ();
};
```

---------------------------------------------
nanSample.cpp
---------------------------------------------
```c++
#include "node.h"
#include "nanSample.h"

Nan::Persistent<FunctionTemplate> nanSample::sampleTemplate_s;

nanSample::nanSample () { }
nanSample::~nanSample () { }

void nanSample::Init ( Handle<Object> target )
{
Nan::HandleScope scope;

Local<FunctionTemplate> temp = Nan::New<FunctionTemplate> (nanSample::New );
temp->InstanceTemplate () -> SetInternalFieldCount ( 1 ) ;
temp->SetClassName ( Nan::New<v8::String> ( "NanSample" ).ToLocalChecked ());

Nan::SetPrototypeMethod ( temp, "PrintHello", PrintHello ) ;

sampleTemplate_s.Reset ( temp );
Nan::Set ( target, Nan::New<v8::String>("NanSample").ToLocalChecked (),
temp->GetFunction () );

}
NAN_METHOD ( nanSample::New )
{
nanSample *sample = new nanSample ();
sample->Wrap ( info.This () );
info.GetReturnValue ().Set ( info.This () );
}

NAN_METHOD (nanSample::PrintHello)
{
Nan::HandleScope scope ;

Local<Function> callback = Local<Function>::Cast ( info[info.Length () - 1] );
sampleBaton *baton = (sampleBaton *)malloc ( sizeof ( sampleBaton ) );
memset ( baton, 0, sizeof ( sampleBaton ) );
baton->req.data = ( void * ) baton;
baton->cb.Reset ( callback );

uv_queue_work ( uv_default_loop (),
&baton->req,
Async_PrintHello,
(uv_after_work_cb) Async_AfterPrintHello );
info.GetReturnValue ().SetUndefined ();
}
void nanSample::Async_PrintHello ( uv_work_t *req )
{
// Nothing to do;
;
}

void nanSample::Async_AfterPrintHello ( uv_work_t *req )
{
Nan::HandleScope scope;
sampleBaton *baton = (sampleBaton *)req->data;
Nan::TryCatch tc;
Local<Value> argv[1], v;
std::string str = "Hello, World\n" ;

v = Nan::New<v8::String> ( ( "Hello, World\n")).ToLocalChecked () ;
argv[0] = v;
Local<Function> callback = Nan::New<Function>( baton->cb );
delete baton ;

Nan::MakeCallback ( Nan::GetCurrentContext ()->Global (),
callback,
1,
argv );
if ( tc.HasCaught () )
Nan::FatalException ( tc ) ;
}

extern "C"
{
static void init (Handle<Object> target )
{
nanSample::Init (target ) ;
}
NODE_MODULE (nanSample, init );
}
```
---------------------------------------------
Application webapp.js
---------------------------------------------
```javascript
var http = require ( 'http' ) ;
var url = require ( 'url' ) ;
var ns = require ('nanSample');
var portid = 8133 ;

http.createServer (
function ( request, response )
{
var urlparts = request.url.split ( "/" ) ;
htmlHeader ( response,
"Sample App",
"With NanSample to test memory leaks" );
ns.PrintHello (
function ( arg )
{

console.log ( arg ) ;

// response.write ( arg ) ;
htmlFooter ( response ) ;
}

);

}
).listen ( portid, "localhost" ) ;
console.log ( "Server running at http://localhost:" + portid ) ;
// Prepare HTML header
function htmlHeader(response, title, caption)
{
response.writeHead (200, {"Content-Type" : "text/html" });
response.write ("<!DOCTYPE html>");
response.write ("<html>");
response.write ("<head>");
response.write ("<style>"
+ "body {background:#FFFFFF;color:#000000;font-family:Arial,sans-serif;margin:40px;padding:10px;font-size:12px;text-align:center;}"
+ "h1 {margin:0px;margin-bottom:12px;background:#FF0000;text-align:center;color:#FFFFFF;font-size:28px;}"
+ "table {border-collapse: collapse; margin-left:auto; margin-right:auto;}"
+ "td {padding:8px;border-style:solid}"
+ "</style>\n");
response.write ("<title>" + caption + "</title>");
response.write ("</head>");
response.write ("<body>");
response.write ("<h1>" + title + "</h1>");
}

// Prepare HTML footer
function htmlFooter(response)
{
response.write("</body>\n</html>");
response.end();
}
```

**Comment by kkoopa** [comment] 2015-11-06 23:27
The only thing that sticks out is that you never reset the persistent handle in the baton. It is advisable to use [AsyncWorker](https://github.com/nodejs/nan/blob/master/doc/asyncworker.md#api_nan_async_worker) to avoid this kind of problem.

**Comment by bjouhier** [comment] 2015-11-07 12:05
+1. It's preventing us from upgrading one of our branches to node 4.2.

**Comment by Raydekk** [comment] 2015-11-07 12:08
+1 same here

**Comment by kkoopa** [comment] 2015-11-07 13:59
The issue here is that there is a leak in their code, due to lack of proper disposal of persistent handles. This applies both to the sample code provided here, and to the code in the referenced pull request. I will now close this issue, but it can be reopened if the original poster's problem with a reproducible leak remains after said problems have been fixed.

**Closed by kkoopa** 2015-11-07 13:59 UTC

**Comment by cjbj** [comment] 2015-11-08 13:53
@kkoopa thanks for commenting.  @pvenkatraman tells me that your suggestion seems to be working in the testcase, and he will schedule some load testing of node-oracledb.

**Comment by marlic7** [comment] 2015-11-09 08:31
+1

**Comment by bnoordhuis** [comment] 2015-11-09 10:29
@marlic7 Why the +1?

**Comment by cjbj** [comment] 2015-11-09 12:18
I was encouraging +1's to highlight the importance :)

**Comment by bnoordhuis** [comment] 2015-11-09 13:04
@cjbj @marlic7 The issue is closed and the bug turned out to be not in nan.  Meaningful feedback is still welcome but I don't consider context-less +1s meaningful, it just spams up maintainers' inboxes.

(I get 150-200 GH emails every day.  I get grumpy about these things.)

**Comment by pvenkatraman** [comment] 2015-11-11 10:05
Added baton->cb.Reset () to clear the persistent callback function pointer before "delete baton".  This clears the memory leak for me.  Thanks for all the suggestions.

**Comment by tjwebb** [comment] 2015-11-13 17:15
+1
