### ISSUE TITLE
node v12 error: too few arguments to function call, expected 2, have 1

### ISSUE THREAD

**Issue by loretoparisi** [nodejs/nan#877] opened 2019-11-19 14:54 UTC
It fails when in `node lts`, i.e.

```
$ node --version
v12.13.1
$ npm --version
6.13.1
```

and also in `v12.13.0`.

```
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:8:
../src/common.h:32:38: error: too few arguments to function call, single argument 'context' was not specified
    ? options->Get(key)->Uint32Value()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/batch.cc:42:67: error: no matching member function for call to 'ToObject'
  Database* database = Nan::ObjectWrap::Unwrap<Database>(info[0]->ToObject());
                                                         ~~~~~~~~~^~~~~~~~
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/batch.cc:72:69: error: too few arguments to function call, single argument 'context' was not specified
    maybeInstance = Nan::NewInstance(constructorHandle->GetFunction(), 1, argv);
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/batch.cc:75:69: error: too few arguments to function call, single argument 'context' was not specified
    maybeInstance = Nan::NewInstance(constructorHandle->GetFunction(), 2, argv);
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/batch.cc:91:3: error: no matching member function for call to 'ToObject'
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/leveldown.h:53:21: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
  } else if (!from->ToObject().IsEmpty()                                       \
              ~~~~~~^~~~~~~~
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/batch.cc:91:3: error: no matching member function for call to 'ToObject'
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/leveldown.h:54:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
      && node::Buffer::HasInstance(from->ToObject())) {                        \
                                   ~~~~~~^~~~~~~~
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/batch.cc:91:3: error: no matching member function for call to 'ToObject'
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/leveldown.h:55:44: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                     ~~~~~~^~~~~~~~
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7 warnings and 20 errors generated.
```

**Comment by addaleax** [comment] 2019-11-19 15:02
This looks more like an issue with whatever project you are compiling, and not nan itself?

**Comment by loretoparisi** [comment] 2019-11-19 15:12
So `nan` depends on

```
│ ├─┬ java@0.12.0
│ │ ├─┬ async@2.6.1
│ │ │ └── lodash@4.17.14 deduped
│ │ ├─┬ find-java-home@0.2.0
│ │ │ ├── which@1.0.9
│ │ │ └── winreg@1.2.4
│ │ ├─┬ glob@7.1.3
│ │ │ ├── fs.realpath@1.0.0 deduped
│ │ │ ├── inflight@1.0.6 deduped
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── minimatch@3.0.4 deduped
│ │ │ ├── once@1.4.0 deduped
│ │ │ └── path-is-absolute@1.0.1 deduped
│ │ ├── lodash@4.17.14
│ │ └── nan@2.14.0 deduped
```

```
 │ └─┬ websocket@1.0.30
│ │   ├── debug@2.6.9 deduped
│ │   ├── nan@2.14.0 deduped
```

```
│ │ │ ├─┬ leveldown@4.0.2
│ │ │ │ ├─┬ abstract-leveldown@5.0.0
│ │ │ │ │ └── xtend@4.0.2 deduped
│ │ │ │ ├── bindings@1.3.1
│ │ │ │ ├── fast-future@1.0.2
│ │ │ │ ├── nan@2.12.1
```

```
│ │ ├─┬ level-sublevel@6.6.5
│ │ │ ├─┬ bytewise@1.1.0
│ │ │ │ ├─┬ bytewise-core@1.2.3
│ │ │ │ │ └── typewise-core@1.2.0
│ │ │ │ └─┬ typewise@1.0.3
│ │ │ │   └── typewise-core@1.2.0 deduped
│ │ │ ├─┬ levelup@0.19.1
│ │ │ │ ├─┬ bl@0.8.2
│ │ │ │ │ └── readable-stream@1.0.34 deduped
│ │ │ │ ├─┬ deferred-leveldown@0.2.0
│ │ │ │ │ └─┬ abstract-leveldown@0.12.4
│ │ │ │ │   └── xtend@3.0.0
│ │ │ │ ├─┬ errno@0.1.7
│ │ │ │ │ └── prr@1.0.1
│ │ │ │ ├── prr@0.0.0
│ │ │ │ ├─┬ readable-stream@1.0.34
│ │ │ │ │ ├── core-util-is@1.0.2 deduped
│ │ │ │ │ ├── inherits@2.0.4 deduped
│ │ │ │ │ ├── isarray@0.0.1
│ │ │ │ │ └── string_decoder@0.10.31
│ │ │ │ ├── semver@5.1.1
│ │ │ │ └── xtend@3.0.0
│ │ │ ├── ltgt@2.1.3
│ │ │ ├── pull-defer@0.2.3
│ │ │ ├─┬ pull-level@2.0.4
│ │ │ │ ├─┬ level-post@1.0.7
│ │ │ │ │ └── ltgt@2.1.3 deduped
│ │ │ │ ├── pull-cat@1.1.11
│ │ │ │ ├─┬ pull-live@1.0.1
│ │ │ │ │ ├── pull-cat@1.1.11 deduped
│ │ │ │ │ └── pull-stream@3.6.14 deduped
│ │ │ │ ├── pull-pushable@2.2.0
│ │ │ │ ├── pull-stream@3.6.14 deduped
│ │ │ │ ├─┬ pull-window@2.1.4
│ │ │ │ │ └── looper@2.0.0
│ │ │ │ └─┬ stream-to-pull-stream@1.7.3
│ │ │ │   ├── looper@3.0.0
│ │ │ │   └── pull-stream@3.6.14 deduped
│ │ │ ├── pull-stream@3.6.14
│ │ │ ├── typewiselite@1.0.0
│ │ │ └── xtend@4.0.2 deduped
│ │ └── nan@2.14.0
```

```
│ ├─┬ couchbase@2.6.9
│ │ ├── bindings@1.5.0 deduped
│ │ ├── dev-null@0.1.1
│ │ ├── nan@2.14.0 deduped
```

```
│ │ │ │ │ ├─┬ string-width@1.0.2
│ │ │ │ │ │ ├── code-point-at@1.1.0
│ │ │ │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ │ │ │ └── number-is-nan@1.0.1
```

...

How can I get rid of this mess then?

**Comment by loretoparisi** [comment] 2019-11-19 15:21
**[UPDATE]**
The only thing I can see from logging, is the `leveldb` was the log just before the first `nan` error:

```
prebuild-install WARN install No prebuilt binaries found (target=12.13.1 runtime=node arch=x64 libc= platform=darwin)
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
In file included from ../node_modules/nan/nan.h:222:
In file included from ../node_modules/nan/nan_converters.h:67:
../node_modules/nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../node_modules/nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:214:1: note: expanded from here
ToBoolean
^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2567:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATED("ToBoolean can never throw. Use Local version.",
  ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../node_modules/nan/nan.h:222:
In file included from ../node_modules/nan/nan_converters.h:67:
../node_modules/nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../node_modules/nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:221:1: note: expanded from here
BooleanValue
^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2605:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/loretoparisi/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../node_modules/nan/nan.h:223:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
```

**Comment by bnoordhuis** [comment] 2019-11-19 16:03
The problem is that leveldown depends on nan@2.12.1, which is too old. I see you've opened an issue over at leveldown, I'm closing this one.

**Closed by bnoordhuis** 2019-11-19 16:03 UTC
